modLoader = "javafml"
loaderVersion = "[${forge_loader_version},)"
issueTrackerURL = "https://github.com/Discusser/TooManyEntities/issues"
license = "MIT"

[[mods]]
modId = "too_many_entities"
logoFile = "icon.png"
version = "${version}"
displayName = "Too Many Entities"
authors = "Discusser"
description = '''
This mod allows you to hide extra entities in order to reduce lag, especially with mob farms. The mobs still exist in the world, they are just not visible.
'''

[[dependencies.too_many_entities]]
modId = "forge"
mandatory = true
versionRange = "[${forge_loader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.too_many_entities]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.too_many_entities]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.too_many_entities]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"

[[dependencies.too_many_entities]]
modId = "entityculling"
mandatory = false
versionRange = "[${entity_culling_version},)"
side = "CLIENT"