modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Discusser/TooManyEntities/issues"
license = "MIT"

[[mods]]
modId = "too_many_entities"
logoFile = "assets/too_many_entities/icon.png"
version = "${version}"
displayName = "Too Many Entities"
authors = "Discusser"
description = '''
This mod allows you to hide extra entities in order to reduce lag, especially with mob farms. The mobs still exist in the world, they are just not visible.
'''
#logoFile = ""

[[dependencies.too_many_entities]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.too_many_entities]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.too_many_entities]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.too_many_entities]]
modId = "cloth_config"
mandatory = true
versionRange = "11.1.118"

[[dependencies.too_many_entities]]
modId = "entityculling"
mandatory = false
versionRange = "1.6.6"
ordering = "BEFORE"
side = "CLIENT"
