plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

repositories {
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases/" }
}

dependencies {
    api "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    api "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"
    api files("${rootProject.projectDir}/libs/architectury-19.0.1-fabric.jar")

    api("me.shedaniel.cloth:cloth-config-fabric:$project.clothconfig_version") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    compileOnly "com.terraformersmc:modmenu:$project.modmenu_version"
    localRuntime "com.terraformersmc:modmenu:$project.modmenu_version"

    compileOnly("maven.modrinth:entityculling:$project.entityculling_version-fabric,$project.minecraft_version")

    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'fabric_loader_version', fabric_loader_version
    inputs.property 'fabric_api_version', fabric_api_version
    inputs.property 'fabric_minecraft_version_range', fabric_minecraft_version_range
    inputs.property 'architectury_api_version', architectury_api_version
    inputs.property 'clothconfig_version', clothconfig_version
    inputs.property 'entityculling_version', entityculling_version
    inputs.property 'modmenu_version', modmenu_version

    filesMatching('fabric.mod.json') {
        expand(version: project.version, fabric_loader_version: fabric_loader_version, fabric_api_version: fabric_api_version,
                fabric_minecraft_version_range: fabric_minecraft_version_range, architectury_api_version: architectury_api_version,
                clothconfig_version: clothconfig_version, entityculling_version: entityculling_version,
                modmenu_version: modmenu_version)
    }
}

jar {
    archiveClassifier = 'raw'
}

shadowJar {
    dependsOn(jar)
    from(zipTree(jar.archiveFile))

    exclude "architectury.common.json"
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

sourcesJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
