# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.2b
maven_group = io.github.discusser.toomanyentities
archives_name = too_many_entities
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.19.2
yarn_mappings = 1.19.2+build.28

# Dependencies
architectury_api_version = 6.6.92
fabric_loader_version = 0.16.9
fabric_api_version = 0.77.0+1.19.2
forge_version = 1.19.2-43.4.0
forge_loader_version = 43

# Dependencies
clothconfig_version=8.3.134
modmenu_version=4.2.0-beta.2
entityculling_version=1.6.1
