# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.2.0
maven_group = io.github.discusser.toomanyentities
archives_name = too_many_entities
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.4
yarn_mappings = 1.21.4+build.8

# Dependencies
architectury_api_version = 15.0.3
fabric_loader_version = 0.16.14
fabric_api_version = 0.119.3+1.21.4
neoforge_version = 21.4.140
yarn_mappings_patch_neoforge_version = 1.21+build.4

# Dependencies
clothconfig_version=17.0.144
modmenu_version=13.0.3
entityculling_version=1.7.4
#transition_version=1.0.2
#transition_version_date=20250619.203101-2
#trender_version=1.0.4
#trender_version_date=20250619-204757-2
