architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    compileOnly "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    compileOnly files("${rootProject.projectDir}/libs/architectury-19.0.1-fabric.jar")

    compileOnlyApi("me.shedaniel.cloth:cloth-config:$project.clothconfig_version")
    compileOnly("maven.modrinth:entityculling:$project.entityculling_version-fabric,$project.minecraft_version")
}
