modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Discusser/TooManyEntities/issues"
license = "MIT"

[[mods]]
modId = "too_many_entities"
logoFile = "assets/too_many_entities/icon.png"
version = "${version}"
displayName = "Too Many Entities"
authors = "Discusser"
description = '''
This mod allows you to hide extra entities in order to reduce lag, especially with mob farms. The mobs still exist in the world, they are just not visible.
'''

[[dependencies.too_many_entities]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.too_many_entities]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.too_many_entities]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.too_many_entities]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.0,)"

[[dependencies.too_many_entities]]
modId = "entityculling"
type = "optional"
versionRange = "[1.7.0,)"
side = "CLIENT"

[[mixins]]
config = "too_many_entities-neoforge.mixins.json"
[[mixins]]
config = "too_many_entities.mixins.json"