modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Discusser/TooManyEntities/issues"
license = "MIT"

[[mods]]
modId = "too_many_entities"
logoFile = "assets/too_many_entities/icon.png"
version = "${version}"
displayName = "Too Many Entities"
authors = "Discusser"
description = '''
This mod allows you to hide extra entities in order to reduce lag, especially with mob farms. The mobs still exist in the world, they are just not visible.
'''

[[dependencies.too_many_entities]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.too_many_entities]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.too_many_entities]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.too_many_entities]]
modId = "cloth_config"
type = "required"
versionRange = "[${clothconfig_version},)"

[[dependencies.too_many_entities]]
modId = "entityculling"
type = "optional"
versionRange = "[${entityculling_version},)"
side = "CLIENT"

[[mixins]]
config = "too_many_entities-neoforge.mixins.json"
[[mixins]]
config = "too_many_entities.mixins.json"