plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    api "dev.architectury:architectury-neoforge:$rootProject.architectury_api_version"

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.0"))
    implementation(include("io.github.llamalad7:mixinextras-neoforge:0.4.0"))

    api("me.shedaniel.cloth:cloth-config-neoforge:$project.clothconfig_version")

    compileOnly("maven.modrinth:entityculling:$project.entityculling_version-fabric,$project.minecraft_version")

    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'neoforge_version', neoforge_version
    inputs.property 'neoforge_minecraft_version_range', neoforge_minecraft_version_range
    inputs.property 'architectury_api_version', architectury_api_version
    inputs.property 'clothconfig_version', clothconfig_version
    inputs.property 'entityculling_version', entityculling_version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand(version: project.version, neoforge_version: neoforge_version, neoforge_minecraft_version_range: neoforge_minecraft_version_range,
                architectury_api_version: architectury_api_version, clothconfig_version: clothconfig_version,
                entityculling_version: entityculling_version)
    }
}

jar {
    archiveClassifier = 'raw'
}

shadowJar {
    dependsOn(jar)
    from(zipTree(jar.archiveFile))

    exclude "fabric.mod.json"
    exclude "architectury.common.json"
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

sourcesJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
